// Desi Trivia Race - question bank
// Each question: { q, options: [4], answer: <index 0-3>, cat, diff }
// cat: bollywood | food | states | general | cricket | pop
// diff: easy | medium | hard

const QUESTIONS = [
  // ---------- BOLLYWOOD ----------
  { q: '"Kitne aadmi the?" — which film gave us this line?', options: ['Deewaar', 'Sholay', 'Don', 'Zanjeer'], answer: 1, cat: 'bollywood', diff: 'easy' },
  { q: '"Mogambo khush hua" was said by the villain of which film?', options: ['Mr. India', 'Shaan', 'Karma', 'Tridev'], answer: 0, cat: 'bollywood', diff: 'easy' },
  { q: 'Which film has been running at Mumbai\'s Maratha Mandir for over 25 years?', options: ['Hum Aapke Hain Koun', 'Maine Pyar Kiya', 'Dilwale Dulhania Le Jayenge', 'Kuch Kuch Hota Hai'], answer: 2, cat: 'bollywood', diff: 'easy' },
  { q: 'Amitabh Bachchan made his acting debut in which film?', options: ['Anand', 'Saat Hindustani', 'Zanjeer', 'Bombay to Goa'], answer: 1, cat: 'bollywood', diff: 'medium' },
  { q: '"3 Idiots" was adapted from which novel?', options: ['Revolution 2020', 'Five Point Someone', 'The White Tiger', 'Half Girlfriend'], answer: 1, cat: 'bollywood', diff: 'easy' },
  { q: 'Which Indian film was nominated for the Best Foreign Language Film Oscar in 2002?', options: ['Devdas', 'Lagaan', 'Dil Chahta Hai', 'Kabhi Khushi Kabhie Gham'], answer: 1, cat: 'bollywood', diff: 'easy' },
  { q: 'Kishore Kumar\'s real birth name was:', options: ['Abhas Kumar Ganguly', 'Ashok Kumar Ganguly', 'Kishore Kumar Roy', 'Anup Kumar Ganguly'], answer: 0, cat: 'bollywood', diff: 'hard' },
  { q: '"Gully Boy" was largely inspired by which two real-life rappers?', options: ['Badshah and Raftaar', 'Divine and Naezy', 'Emiway and Krsna', 'Honey Singh and Ikka'], answer: 1, cat: 'bollywood', diff: 'medium' },
  { q: 'Which film won A.R. Rahman his first Academy Awards?', options: ['Rockstar', 'Roja', 'Slumdog Millionaire', 'Dil Se'], answer: 2, cat: 'bollywood', diff: 'easy' },
  { q: 'Yash Raj Films was founded by:', options: ['Yash Johar', 'Yash Chopra', 'B.R. Chopra', 'Subhash Ghai'], answer: 1, cat: 'bollywood', diff: 'medium' },
  { q: '"Taare Zameen Par" centres on a child dealing with:', options: ['Autism', 'Dyslexia', 'ADHD', 'Stammering'], answer: 1, cat: 'bollywood', diff: 'easy' },
  { q: 'Who directed "Kabhi Khushi Kabhie Gham"?', options: ['Aditya Chopra', 'Karan Johar', 'Sooraj Barjatya', 'Sanjay Leela Bhansali'], answer: 1, cat: 'bollywood', diff: 'easy' },
  { q: 'Which 1957 film was India\'s first Oscar nomination for Best Foreign Language Film?', options: ['Mother India', 'Pyaasa', 'Do Bigha Zamin', 'Awaara'], answer: 0, cat: 'bollywood', diff: 'medium' },
  { q: 'In "Sholay", what was the name of Basanti\'s horse?', options: ['Chetak', 'Badal', 'Dhanno', 'Bijli'], answer: 2, cat: 'bollywood', diff: 'medium' },
  { q: 'Farhan Akhtar played which athlete in a 2013 biopic?', options: ['Milkha Singh', 'P.T. Usha', 'Dhyan Chand', 'Abhinav Bindra'], answer: 0, cat: 'bollywood', diff: 'easy' },
  { q: 'Rajesh Khanna is popularly remembered as Hindi cinema\'s:', options: ['First superstar', 'Angry young man', 'Tragedy king', 'Showman'], answer: 0, cat: 'bollywood', diff: 'medium' },
  { q: 'Which actor is nicknamed the "Tragedy King" of Hindi cinema?', options: ['Raj Kapoor', 'Dev Anand', 'Dilip Kumar', 'Guru Dutt'], answer: 2, cat: 'bollywood', diff: 'medium' },
  { q: '"Munna Bhai M.B.B.S." starred which actor in the title role?', options: ['Salman Khan', 'Sanjay Dutt', 'Ajay Devgn', 'Akshay Kumar'], answer: 1, cat: 'bollywood', diff: 'easy' },
  { q: 'Raj Kapoor\'s iconic film studio was named:', options: ['RK Films', 'Kapoor Studios', 'Prithvi Films', 'Navketan'], answer: 0, cat: 'bollywood', diff: 'medium' },
  { q: 'Which song from "Dil Se" was famously shot on top of a moving train?', options: ['Jiya Jale', 'Chaiyya Chaiyya', 'Satrangi Re', 'Ae Ajnabi'], answer: 1, cat: 'bollywood', diff: 'easy' },
  { q: 'Lata Mangeshkar and Asha Bhosle were sisters from which musical family?', options: ['Mangeshkar', 'Burman', 'Ghosh', 'Chopra'], answer: 0, cat: 'bollywood', diff: 'easy' },
  { q: '"Sholay" was released in which year?', options: ['1971', '1973', '1975', '1978'], answer: 2, cat: 'bollywood', diff: 'medium' },

  // ---------- FOOD ----------
  { q: 'Litti Chokha is the signature dish of which state?', options: ['Bihar', 'Uttar Pradesh', 'Jharkhand', 'Chhattisgarh'], answer: 0, cat: 'food', diff: 'easy' },
  { q: 'Dal Baati Churma comes from:', options: ['Gujarat', 'Rajasthan', 'Madhya Pradesh', 'Haryana'], answer: 1, cat: 'food', diff: 'easy' },
  { q: 'Which city is famous for its "Poha-Jalebi" breakfast combo?', options: ['Bhopal', 'Indore', 'Nagpur', 'Jaipur'], answer: 1, cat: 'food', diff: 'medium' },
  { q: 'Agra is most famous for which sweet?', options: ['Peda', 'Petha', 'Ghevar', 'Balushahi'], answer: 1, cat: 'food', diff: 'easy' },
  { q: 'The famous peda comes from which UP city associated with Krishna?', options: ['Vrindavan', 'Mathura', 'Ayodhya', 'Gokul'], answer: 1, cat: 'food', diff: 'medium' },
  { q: 'Ghevar is a disc-shaped sweet traditionally eaten during which festival?', options: ['Diwali', 'Holi', 'Teej', 'Karwa Chauth'], answer: 2, cat: 'food', diff: 'medium' },
  { q: 'Bal Mithai, a brown chocolate-like fudge, is a specialty of:', options: ['Himachal Pradesh', 'Uttarakhand', 'Sikkim', 'Nepal border towns of Bihar'], answer: 1, cat: 'food', diff: 'hard' },
  { q: 'Tunday Kababi of Lucknow is legendary for which kebab?', options: ['Seekh kebab', 'Galouti kebab', 'Shami kebab', 'Boti kebab'], answer: 1, cat: 'food', diff: 'medium' },
  { q: 'Sattu, a summer staple drink and flour, is most associated with:', options: ['Bihar', 'Odisha', 'Punjab', 'Bengal'], answer: 0, cat: 'food', diff: 'easy' },
  { q: 'Thandai is most strongly associated with which festival?', options: ['Holi', 'Diwali', 'Navratri', 'Raksha Bandhan'], answer: 0, cat: 'food', diff: 'easy' },
  { q: '"Daulat ki Chaat", a frothy winter dessert, is a specialty of:', options: ['Lucknow', 'Old Delhi', 'Varanasi', 'Amritsar'], answer: 1, cat: 'food', diff: 'hard' },
  { q: 'Pyaaz Kachori is most famously associated with which Rajasthani city?', options: ['Udaipur', 'Jodhpur', 'Bikaner', 'Ajmer'], answer: 1, cat: 'food', diff: 'hard' },
  { q: 'Bhutte ka Kees, a grated corn snack, belongs to which state\'s street food?', options: ['Maharashtra', 'Madhya Pradesh', 'Gujarat', 'Rajasthan'], answer: 1, cat: 'food', diff: 'hard' },
  { q: 'Misal Pav is a spicy breakfast dish from:', options: ['Gujarat', 'Maharashtra', 'Goa', 'Karnataka'], answer: 1, cat: 'food', diff: 'easy' },
  { q: 'Dhokla is a steamed snack originating from:', options: ['Gujarat', 'Rajasthan', 'Maharashtra', 'Punjab'], answer: 0, cat: 'food', diff: 'easy' },
  { q: 'Which city is most famous for Banarasi Paan?', options: ['Kanpur', 'Varanasi', 'Allahabad', 'Gorakhpur'], answer: 1, cat: 'food', diff: 'easy' },
  { q: 'Chole Bhature is most strongly associated with which region?', options: ['Punjab and Delhi', 'Bengal', 'Kerala', 'Assam'], answer: 0, cat: 'food', diff: 'easy' },
  { q: 'Mysore Pak is a sweet from which state?', options: ['Tamil Nadu', 'Karnataka', 'Andhra Pradesh', 'Kerala'], answer: 1, cat: 'food', diff: 'easy' },
  { q: 'Hyderabadi Biryani is traditionally cooked using which technique?', options: ['Tandoor', 'Dum', 'Bhuna', 'Tawa'], answer: 1, cat: 'food', diff: 'medium' },
  { q: 'Makhan Malai (Nimish), a winter-only dessert, is famous in:', options: ['Lucknow', 'Jaipur', 'Patna', 'Bhopal'], answer: 0, cat: 'food', diff: 'hard' },
  { q: 'Kesar and dry fruits define which thick, chilled North Indian summer drink?', options: ['Thandai', 'Aam Panna', 'Jaljeera', 'Chaas'], answer: 0, cat: 'food', diff: 'medium' },
  { q: 'Bedmi Puri with aloo sabzi is a classic breakfast of which region?', options: ['Western UP and Delhi', 'Coastal Karnataka', 'Assam', 'Kerala'], answer: 0, cat: 'food', diff: 'hard' },

  // ---------- STATES (Hindi belt heavy) ----------
  { q: 'What is the capital of Uttar Pradesh?', options: ['Kanpur', 'Lucknow', 'Varanasi', 'Allahabad'], answer: 1, cat: 'states', diff: 'easy' },
  { q: 'Patna is the capital of:', options: ['Jharkhand', 'Bihar', 'Odisha', 'Chhattisgarh'], answer: 1, cat: 'states', diff: 'easy' },
  { q: 'What is the capital of Madhya Pradesh?', options: ['Indore', 'Gwalior', 'Bhopal', 'Jabalpur'], answer: 2, cat: 'states', diff: 'easy' },
  { q: 'Raipur is the capital of which state?', options: ['Jharkhand', 'Chhattisgarh', 'Odisha', 'Madhya Pradesh'], answer: 1, cat: 'states', diff: 'medium' },
  { q: 'Ranchi is the capital of:', options: ['Bihar', 'Jharkhand', 'Chhattisgarh', 'West Bengal'], answer: 1, cat: 'states', diff: 'easy' },
  { q: 'Which is India\'s largest state by area?', options: ['Madhya Pradesh', 'Maharashtra', 'Rajasthan', 'Uttar Pradesh'], answer: 2, cat: 'states', diff: 'easy' },
  { q: 'Which is India\'s most populous state?', options: ['Bihar', 'Maharashtra', 'Uttar Pradesh', 'West Bengal'], answer: 2, cat: 'states', diff: 'easy' },
  { q: 'Shimla is the capital of:', options: ['Uttarakhand', 'Himachal Pradesh', 'Jammu & Kashmir', 'Sikkim'], answer: 1, cat: 'states', diff: 'easy' },
  { q: 'Chandigarh serves as the shared capital of which two states?', options: ['Punjab and Haryana', 'Haryana and Delhi', 'Punjab and Himachal', 'Haryana and Rajasthan'], answer: 0, cat: 'states', diff: 'easy' },
  { q: 'The Khajuraho temples are located in which state?', options: ['Rajasthan', 'Madhya Pradesh', 'Uttar Pradesh', 'Odisha'], answer: 1, cat: 'states', diff: 'medium' },
  { q: 'The ancient Nalanda University ruins are in which state?', options: ['Uttar Pradesh', 'Bihar', 'Jharkhand', 'West Bengal'], answer: 1, cat: 'states', diff: 'medium' },
  { q: 'Bodh Gaya, where the Buddha attained enlightenment, is in:', options: ['Bihar', 'Uttar Pradesh', 'Nepal', 'Jharkhand'], answer: 0, cat: 'states', diff: 'medium' },
  { q: 'Sarnath, where the Buddha gave his first sermon, is near which city?', options: ['Patna', 'Varanasi', 'Gaya', 'Lucknow'], answer: 1, cat: 'states', diff: 'medium' },
  { q: 'The Sanchi Stupa is located in:', options: ['Madhya Pradesh', 'Maharashtra', 'Bihar', 'Uttar Pradesh'], answer: 0, cat: 'states', diff: 'medium' },
  { q: 'Hawa Mahal is a landmark of which city?', options: ['Udaipur', 'Jodhpur', 'Jaipur', 'Jaisalmer'], answer: 2, cat: 'states', diff: 'easy' },
  { q: 'Jim Corbett National Park, India\'s first national park, is in:', options: ['Uttarakhand', 'Uttar Pradesh', 'Himachal Pradesh', 'Madhya Pradesh'], answer: 0, cat: 'states', diff: 'medium' },
  { q: 'The Ganga originates from which glacier region?', options: ['Yamunotri', 'Gangotri', 'Kedarnath', 'Badrinath'], answer: 1, cat: 'states', diff: 'medium' },
  { q: 'Uttarakhand\'s "Char Dham" includes Kedarnath, Badrinath, Gangotri and:', options: ['Haridwar', 'Rishikesh', 'Yamunotri', 'Nainital'], answer: 2, cat: 'states', diff: 'medium' },
  { q: 'The Kumbh Mela rotates between Prayagraj, Haridwar, Nashik and:', options: ['Varanasi', 'Ujjain', 'Mathura', 'Puri'], answer: 1, cat: 'states', diff: 'medium' },
  { q: 'Kanha and Bandhavgarh tiger reserves are both in which state?', options: ['Madhya Pradesh', 'Chhattisgarh', 'Maharashtra', 'Rajasthan'], answer: 0, cat: 'states', diff: 'medium' },
  { q: 'The Chambal ravines are spread across MP, Rajasthan and:', options: ['Gujarat', 'Uttar Pradesh', 'Haryana', 'Bihar'], answer: 1, cat: 'states', diff: 'hard' },
  { q: 'Ayodhya is located on the banks of which river?', options: ['Ganga', 'Yamuna', 'Sarayu', 'Gomti'], answer: 2, cat: 'states', diff: 'hard' },
  { q: 'Lucknow sits on the banks of which river?', options: ['Gomti', 'Ganga', 'Yamuna', 'Ghaghara'], answer: 0, cat: 'states', diff: 'medium' },
  { q: 'Bihar Diwas, celebrating the state\'s formation, is observed on:', options: ['22 March', '1 November', '15 August', '26 January'], answer: 0, cat: 'states', diff: 'hard' },
  { q: 'Which state was carved out of Bihar in the year 2000?', options: ['Chhattisgarh', 'Jharkhand', 'Uttarakhand', 'Odisha'], answer: 1, cat: 'states', diff: 'medium' },
  { q: 'Uttarakhand was carved out of which state in 2000?', options: ['Himachal Pradesh', 'Uttar Pradesh', 'Haryana', 'Punjab'], answer: 1, cat: 'states', diff: 'easy' },
  { q: 'The Statue of Unity, world\'s tallest statue, stands in:', options: ['Maharashtra', 'Gujarat', 'Madhya Pradesh', 'Rajasthan'], answer: 1, cat: 'states', diff: 'easy' },
  { q: 'The Golden Temple is located in which city?', options: ['Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala'], answer: 1, cat: 'states', diff: 'easy' },

  // ---------- GENERAL INDIA ----------
  { q: 'Who wrote India\'s national anthem "Jana Gana Mana"?', options: ['Bankim Chandra Chattopadhyay', 'Rabindranath Tagore', 'Sarojini Naidu', 'Muhammad Iqbal'], answer: 1, cat: 'general', diff: 'easy' },
  { q: '"Vande Mataram" first appeared in which novel?', options: ['Anandamath', 'Godaan', 'Gora', 'Devdas'], answer: 0, cat: 'general', diff: 'medium' },
  { q: 'India\'s national animal is the:', options: ['Lion', 'Bengal tiger', 'Elephant', 'Leopard'], answer: 1, cat: 'general', diff: 'easy' },
  { q: 'The Indian rupee symbol (₹) was designed by:', options: ['Udaya Kumar', 'Raghuram Rajan', 'Nandan Nilekani', 'D. Udaya Shankar'], answer: 0, cat: 'general', diff: 'hard' },
  { q: 'India\'s Constitution came into effect on:', options: ['15 August 1947', '26 November 1949', '26 January 1950', '2 October 1950'], answer: 2, cat: 'general', diff: 'easy' },
  { q: 'Who was India\'s first President?', options: ['Jawaharlal Nehru', 'Rajendra Prasad', 'S. Radhakrishnan', 'Zakir Husain'], answer: 1, cat: 'general', diff: 'easy' },
  { q: 'Rakesh Sharma is famous for being the first Indian to:', options: ['Win an Olympic gold', 'Travel to space', 'Summit Everest', 'Win a Nobel Prize'], answer: 1, cat: 'general', diff: 'easy' },
  { q: 'The highest mountain peak entirely within India is:', options: ['Nanda Devi', 'Kangchenjunga', 'K2', 'Mount Everest'], answer: 0, cat: 'general', diff: 'hard' },
  { q: 'How many states does India currently have?', options: ['27', '28', '29', '30'], answer: 1, cat: 'general', diff: 'medium' },
  { q: 'India\'s national fruit is the:', options: ['Banana', 'Mango', 'Jackfruit', 'Guava'], answer: 1, cat: 'general', diff: 'easy' },
  { q: 'Which is officially India\'s national river?', options: ['Yamuna', 'Ganga', 'Brahmaputra', 'Godavari'], answer: 1, cat: 'general', diff: 'easy' },
  { q: 'The Indian Railways network is among the world\'s largest under a:', options: ['Private consortium', 'Single management', 'State-wise system', 'Foreign operator'], answer: 1, cat: 'general', diff: 'medium' },
  { q: 'Diwali in North India primarily celebrates the return of Rama to:', options: ['Mathura', 'Ayodhya', 'Varanasi', 'Hastinapur'], answer: 1, cat: 'general', diff: 'easy' },
  { q: 'Chhath Puja, dedicated to the Sun God, is most widely celebrated in:', options: ['Bihar and eastern UP', 'Kerala', 'Punjab', 'Gujarat'], answer: 0, cat: 'general', diff: 'easy' },
  { q: 'The festival of Onam is celebrated primarily in:', options: ['Tamil Nadu', 'Kerala', 'Karnataka', 'Andhra Pradesh'], answer: 1, cat: 'general', diff: 'easy' },
  { q: 'Bihu is the major harvest festival of which state?', options: ['Odisha', 'Assam', 'West Bengal', 'Manipur'], answer: 1, cat: 'general', diff: 'medium' },
  { q: 'Which Indian city is known as the "Pink City"?', options: ['Jodhpur', 'Jaipur', 'Udaipur', 'Bikaner'], answer: 1, cat: 'general', diff: 'easy' },
  { q: 'Jodhpur is popularly called the:', options: ['Blue City', 'Golden City', 'White City', 'Green City'], answer: 0, cat: 'general', diff: 'medium' },
  { q: 'Jaisalmer is popularly called the:', options: ['Blue City', 'Pink City', 'Golden City', 'City of Lakes'], answer: 2, cat: 'general', diff: 'medium' },
  { q: 'Which city is known as the "City of Nawabs"?', options: ['Hyderabad', 'Lucknow', 'Bhopal', 'Rampur'], answer: 1, cat: 'general', diff: 'medium' },
  { q: 'Kanpur was historically known as the "Manchester of the East" for its:', options: ['Steel mills', 'Textile industry', 'Leather tanneries', 'Sugar mills'], answer: 1, cat: 'general', diff: 'hard' },
  { q: 'The Hindi language is written in which script?', options: ['Brahmi', 'Devanagari', 'Gurmukhi', 'Sharada'], answer: 1, cat: 'general', diff: 'easy' },
  { q: 'Premchand, a towering Hindi and Urdu novelist, wrote which classic?', options: ['Godaan', 'Gitanjali', 'Anandamath', 'Meghdoot'], answer: 0, cat: 'general', diff: 'medium' },

  // ---------- CRICKET ----------
  { q: 'India won the 2011 ODI World Cup final against which team?', options: ['Australia', 'Pakistan', 'Sri Lanka', 'England'], answer: 2, cat: 'cricket', diff: 'easy' },
  { q: 'The 2011 World Cup final was played at which stadium?', options: ['Eden Gardens', 'Wankhede Stadium', 'Chinnaswamy Stadium', 'Feroz Shah Kotla'], answer: 1, cat: 'cricket', diff: 'medium' },
  { q: 'M.S. Dhoni hails from which city?', options: ['Patna', 'Ranchi', 'Raipur', 'Jamshedpur'], answer: 1, cat: 'cricket', diff: 'easy' },
  { q: 'India won the 1983 World Cup final against:', options: ['Australia', 'England', 'West Indies', 'Pakistan'], answer: 2, cat: 'cricket', diff: 'easy' },
  { q: 'Kapil Dev\'s famous unbeaten 175 in the 1983 World Cup came against:', options: ['Zimbabwe', 'Australia', 'England', 'New Zealand'], answer: 0, cat: 'cricket', diff: 'medium' },
  { q: 'Yuvraj Singh hit six sixes in an over during the 2007 T20 World Cup against:', options: ['Brett Lee', 'Stuart Broad', 'Shane Bond', 'Dale Steyn'], answer: 1, cat: 'cricket', diff: 'easy' },
  { q: 'Which stadium is known as the "Mecca of Indian cricket"?', options: ['Wankhede', 'Eden Gardens', 'Chepauk', 'Ferozeshah Kotla'], answer: 1, cat: 'cricket', diff: 'medium' },
  { q: 'Who won the very first IPL season in 2008?', options: ['Chennai Super Kings', 'Rajasthan Royals', 'Mumbai Indians', 'Deccan Chargers'], answer: 1, cat: 'cricket', diff: 'medium' },
  { q: 'Virat Kohli was born in which city?', options: ['Delhi', 'Chandigarh', 'Mumbai', 'Meerut'], answer: 0, cat: 'cricket', diff: 'easy' },
  { q: 'Sachin Tendulkar made his international debut against which country?', options: ['Sri Lanka', 'Pakistan', 'Australia', 'England'], answer: 1, cat: 'cricket', diff: 'medium' },
  { q: 'Which Indian bowler is nicknamed the "Turbanator"?', options: ['Anil Kumble', 'Harbhajan Singh', 'Bishan Singh Bedi', 'Ravichandran Ashwin'], answer: 1, cat: 'cricket', diff: 'medium' },
  { q: 'Anil Kumble famously took how many wickets in a single Test innings vs Pakistan in 1999?', options: ['8', '9', '10', '7'], answer: 2, cat: 'cricket', diff: 'medium' },

  // ---------- DESI POP CULTURE / INTERNET ----------
  { q: 'The viral "Rasode mein kaun tha" remix came from which TV serial?', options: ['Kyunki Saas Bhi Kabhi Bahu Thi', 'Saath Nibhaana Saathiya', 'Kumkum Bhagya', 'Balika Vadhu'], answer: 1, cat: 'pop', diff: 'easy' },
  { q: 'Bhuvan Bam is best known for which YouTube channel?', options: ['BB Ki Vines', 'Ashish Chanchlani Vines', 'TVF', 'Round2Hell'], answer: 0, cat: 'pop', diff: 'easy' },
  { q: 'The Amul mascot is famous for which tagline?', options: ['Taste the Thunder', 'Utterly Butterly Delicious', 'The Complete Man', 'Fill It Shut It Forget It'], answer: 1, cat: 'pop', diff: 'easy' },
  { q: 'Shaktimaan, India\'s iconic TV superhero, was played by:', options: ['Mukesh Khanna', 'Arun Govil', 'Nitish Bharadwaj', 'Gajendra Chauhan'], answer: 0, cat: 'pop', diff: 'medium' },
  { q: 'In the cartoon "Chhota Bheem", which village is the story set in?', options: ['Furfuri Nagar', 'Dholakpur', 'Champakvan', 'Vijaynagar'], answer: 1, cat: 'pop', diff: 'medium' },
  { q: '"Motu Patlu" is set in which fictional town?', options: ['Dholakpur', 'Furfuri Nagar', 'Malgudi', 'Shantivan'], answer: 1, cat: 'pop', diff: 'hard' },
  { q: 'Ramanand Sagar\'s "Ramayan" first aired on which channel?', options: ['Zee TV', 'Doordarshan', 'Sony', 'Star Plus'], answer: 1, cat: 'pop', diff: 'easy' },
  { q: 'The "Binod" meme wave was sparked by a video from which YouTube channel?', options: ['Slayy Point', 'Carryminati', 'Triggered Insaan', 'Harsh Beniwal'], answer: 0, cat: 'pop', diff: 'medium' },
  { q: '"Kacha Badam", the viral song, was originally sung by a peanut seller from:', options: ['Bihar', 'West Bengal', 'Odisha', 'Jharkhand'], answer: 1, cat: 'pop', diff: 'medium' },
  { q: 'TVF\'s hit web series about UPSC aspirants in Delhi is called:', options: ['Kota Factory', 'Aspirants', 'Panchayat', 'Gullak'], answer: 1, cat: 'pop', diff: 'easy' },
  { q: 'The web series "Panchayat" is set in a village in which state?', options: ['Bihar', 'Uttar Pradesh', 'Madhya Pradesh', 'Rajasthan'], answer: 1, cat: 'pop', diff: 'medium' },
  { q: 'Which Indian sitcom features the residents of Gokuldham Society?', options: ['Sarabhai vs Sarabhai', 'Taarak Mehta Ka Ooltah Chashmah', 'Khichdi', 'FIR'], answer: 1, cat: 'pop', diff: 'easy' },
  { q: '"Malgudi Days" was based on the writings of:', options: ['R.K. Narayan', 'Ruskin Bond', 'Mulk Raj Anand', 'Khushwant Singh'], answer: 0, cat: 'pop', diff: 'medium' },
  { q: 'Kota, the coaching hub featured in "Kota Factory", is in which state?', options: ['Madhya Pradesh', 'Rajasthan', 'Gujarat', 'Uttar Pradesh'], answer: 1, cat: 'pop', diff: 'easy' },
];

if (typeof module !== 'undefined') module.exports = QUESTIONS;
